// async function getData(){
//     return "Sourja";
// }
// const res= getData();
// console.log(res);


// async function getData(){
//     const prom= new Promise((resovle,reject)=>{
//         resovle('Hurrah!! Successfully resolved!!');
//     });
//     return prom;
// }
// const res= getData();
// res
//    .then(result=>console.log(result));



// ---- Diff b/w using a promise and async- await function

//-- using Promise

// function b(){
//     return new Promise((resolve,reject)=>{
//         setTimeout(()=>{
//              console.log('Promise');
//         },10000);
       
//     })
// }
// b()
//   .then(res=>console.log(res));
// console.log('hello');
  

// Using async-await function
  
// 
